# Generated by Django 3.0.8 on 2020-08-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSpiderConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiderid', models.IntegerField(db_column='spiderId')),
                ('domain', models.CharField(max_length=255)),
                ('sleeptime', models.IntegerField(blank=True, db_column='sleepTime', null=True)),
                ('listurl', models.CharField(blank=True, db_column='listUrl', max_length=255, null=True)),
                ('detailurl', models.CharField(blank=True, db_column='detailUrl', max_length=255, null=True)),
                ('titlexpath', models.CharField(blank=True, db_column='titleXpath', max_length=255, null=True)),
                ('timexpath', models.CharField(blank=True, db_column='timeXpath', max_length=255, null=True)),
                ('authorxpath', models.CharField(blank=True, db_column='authorXpath', max_length=255, null=True)),
                ('contentxpath', models.TextField(blank=True, db_column='contentXpath', null=True)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('lastupdatetime', models.DateTimeField(blank=True, db_column='lastUpdateTime', null=True)),
            ],
            options={
                'db_table': 't_spider_conf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TSpiderResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confid', models.IntegerField(db_column='confId')),
                ('type', models.CharField(max_length=16)),
                ('url', models.CharField(max_length=500)),
                ('htmlcontent', models.TextField(db_column='htmlContent')),
                ('htmlpath', models.CharField(blank=True, db_column='htmlPath', max_length=128, null=True)),
                ('pdfpath', models.CharField(blank=True, db_column='pdfPath', max_length=128, null=True)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 't_spider_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TSpiderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cronexpression', models.CharField(db_column='cronExpression', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('delflag', models.IntegerField(blank=True, db_column='delFlag', null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(db_column='createTime')),
            ],
            options={
                'db_table': 't_spider_task',
                'managed': True,
            },
        ),
    ]
