# Generated by Django 3.0.8 on 2020-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tspiderconf',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, db_column='createTime', max_length=0),
        ),
        migrations.AlterField(
            model_name='tspiderconf',
            name='lastupdatetime',
            field=models.DateTimeField(auto_now_add=True, db_column='lastUpdateTime', max_length=0, null=True),
        ),
        migrations.AlterField(
            model_name='tspiderresult',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, db_column='createTime', max_length=0),
        ),
        migrations.AlterField(
            model_name='tspidertask',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, db_column='createTime', max_length=0),
        ),
        migrations.AlterField(
            model_name='tspidertask',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
