# Generated by Django 3.0.8 on 2020-08-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20200806_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='authorxpath',
            new_name='authorXpath',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='contentxpath',
            new_name='contentXpath',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='createtime',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='detailurl',
            new_name='detailUrl',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='lastupdatetime',
            new_name='lastupdateTime',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='listurl',
            new_name='listUrl',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='sleeptime',
            new_name='sleepTime',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='spiderid',
            new_name='spiderId',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='timexpath',
            new_name='timeXpath',
        ),
        migrations.RenameField(
            model_name='tspiderconf',
            old_name='titlexpath',
            new_name='titleXpath',
        ),
    ]
