# Generated by Django 3.0.8 on 2020-08-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20200806_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tspiderresult',
            old_name='confid',
            new_name='confId',
        ),
        migrations.RenameField(
            model_name='tspiderresult',
            old_name='createtime',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='tspiderresult',
            old_name='htmlcontent',
            new_name='htmlContent',
        ),
        migrations.RenameField(
            model_name='tspiderresult',
            old_name='htmlpath',
            new_name='htmlPath',
        ),
        migrations.RenameField(
            model_name='tspiderresult',
            old_name='pdfpath',
            new_name='pdfPath',
        ),
        migrations.RenameField(
            model_name='tspidertask',
            old_name='createtime',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='tspidertask',
            old_name='cronexpression',
            new_name='cronExpression',
        ),
        migrations.RenameField(
            model_name='tspidertask',
            old_name='delflag',
            new_name='delFlag',
        ),
    ]
