# Generated by Django 3.0.8 on 2020-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20200806_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspiderresult',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
